controllers:
    resource:
        path: ../src/Controller/Library/
        namespace: App\Controller
    type: attribute
    api_token:
        path: ../src/Controller/Security/
        namespace: App\Controller\Security
